"""
Deterministic, bilingual (English + Norwegian) keyword lookup for a
grocery store_category. Pure function — no network, no model — tried as
a first pass before any AI call, same "no AI dependency" positioning as
services/recipe_import.py's primary path (see docs/DECISIONS.md).
Callers fall back to "other" (today's existing default) when this
returns None, exactly as before this module existed.
"""

from typing import Optional

# Substring matching (not whole-word) is deliberate: Norwegian compounds
# words with no separator (e.g. "kyllingfilet", "gulost"), so a
# word-boundary match would miss the majority of real Norwegian
# ingredient lines. The tradeoff is cross-keyword collisions (e.g. "corn"
# inside "cornstarch", "fisk" inside "fiskekraft") — resolved by
# preferring the *longest* matching keyword, not by category order, so a
# more specific compound match always beats a shorter generic one it
# happens to contain. "frozen" is checked separately, as an unconditional
# override, before that length comparison: it names a store aisle, not an
# ingredient type, so "frozen chicken" belongs in "frozen" even though
# "chicken" (7 chars) is a longer match than "frozen" (6) — length-based
# tie-breaking would otherwise pick the wrong one.
_CATEGORY_ORDER = ("meat", "dairy", "produce", "pantry")

_KEYWORDS: dict[str, tuple[str, ...]] = {
    "frozen": (
        "frozen",
        "frossen",
        "fryst",
        "frosne",
        "ice cream",
        "iskrem",
    ),
    "meat": (
        "chicken",
        "kylling",
        "beef",
        "storfe",
        "biff",
        "pork",
        "svinekjøtt",
        "svin",
        "lamb",
        "lam",
        "turkey",
        "kalkun",
        "bacon",
        "sausage",
        "pølse",
        "ham",
        "skinke",
        "salmon",
        "laks",
        "fish",
        "fisk",
        "shrimp",
        "prawn",
        "reker",
        "tuna",
        "tunfisk",
        "cod",
        "torsk",
        "kjøttdeig",
        "ground beef",
        "steak",
        "ribs",
        "meatball",
        "kjøttbolle",
        "chorizo",
        "pepperoni",
        "duck",
        "andebryst",
        "veal",
        "kalvekjøtt",
    ),
    "dairy": (
        "milk",
        "melk",
        "cream",
        "fløte",
        "kremfløte",
        "yogurt",
        "yoghurt",
        "cheese",
        "ost",
        "butter",
        "smør",
        "egg",
        "sour cream",
        "rømme",
        "cottage cheese",
        "mozzarella",
        "cheddar",
        "parmesan",
        "feta",
        "ricotta",
        "buttermilk",
        "creme fraiche",
        "kesam",
    ),
    "produce": (
        "onion",
        "løk",
        "garlic",
        "hvitløk",
        "tomato",
        "tomat",
        "potato",
        "potet",
        "carrot",
        "gulrot",
        "gulrøtter",
        "celery",
        "selleri",
        "bell pepper",
        "paprika",
        "lettuce",
        "salat",
        "spinach",
        "spinat",
        "broccoli",
        "brokkoli",
        "cucumber",
        "agurk",
        "zucchini",
        "courgette",
        "mushroom",
        "sopp",
        "lemon",
        "sitron",
        "lime",
        "apple",
        "eple",
        "banana",
        "banan",
        "avocado",
        "avokado",
        "ginger",
        "ingefær",
        "cilantro",
        "coriander",
        "koriander",
        "parsley",
        "persille",
        "basil",
        "basilikum",
        "cabbage",
        "kål",
        "kale",
        "grønnkål",
        "leek",
        "purre",
        "scallion",
        "green onion",
        "shallot",
        "sjalottløk",
        "herb",
        "urt",
        "berries",
        "bær",
        "strawberr",
        "jordbær",
        "blueberr",
        "blåbær",
        "grape",
        "drue",
        "orange",
        "appelsin",
        "corn",
        "mais",
        "pea",
        "erter",
        "squash",
        "pumpkin",
        "gresskar",
        "radish",
        "reddik",
        "beet",
        "rødbete",
        "cauliflower",
        "blomkål",
        "asparagus",
        "asparges",
        "dill",
        "chili",
        "chile",
    ),
    "pantry": (
        "flour",
        "mel",
        "hvetemel",
        "sugar",
        "sukker",
        "salt",
        "black pepper",
        "pepper",
        "rice",
        "ris",
        "pasta",
        "noodle",
        "nudler",
        "oil",
        "olje",
        "olivenolje",
        "olive oil",
        "vinegar",
        "eddik",
        "soy sauce",
        "soyasaus",
        "stock",
        "broth",
        "kraft",
        "fiskekraft",
        "kyllingkraft",
        "buljong",
        "spice",
        "krydder",
        "cumin",
        "spisskummen",
        "cinnamon",
        "kanel",
        "honey",
        "honning",
        "syrup",
        "sirup",
        "baking powder",
        "bakepulver",
        "baking soda",
        "natron",
        "yeast",
        "gjær",
        "breadcrumb",
        "brødsmule",
        "bread",
        "brød",
        "canned tomato",
        "hermetisk",
        "tomato paste",
        "tomatpuré",
        "coconut milk",
        "kokosmelk",
        "curry powder",
        "karripulver",
        "chili powder",
        "cornstarch",
        "cornflour",
        "maisstivelse",
        "lentil",
        "linser",
        "bean",
        "bønne",
        "chickpea",
        "kikert",
        "stock cube",
        "buljongterning",
        "tortilla",
        "ketchup",
        "mustard",
        "sennep",
        "mayonnaise",
        "majones",
        "wine",
        "vin",
        "sesame oil",
        "sesamolje",
        "vanilla",
        "vanilje",
        "chocolate",
        "sjokolade",
        "cocoa",
        "kakao",
        "oats",
        "havregryn",
        "quinoa",
        "tea",
        "coffee",
        "kaffe",
        "tofu",
        "taco seasoning",
        "seasoning",
    ),
}


def suggest_category(ingredient_name: str) -> Optional[str]:
    """Suggest a store_category via bilingual keyword lookup, or None if
    nothing matches. Never raises. Callers should fall back to "other"
    (today's existing default) on None, same as before this existed."""
    if not ingredient_name or not ingredient_name.strip():
        return None
    normalized = ingredient_name.strip().lower()
    if any(keyword in normalized for keyword in _KEYWORDS["frozen"]):
        return "frozen"
    best_category: Optional[str] = None
    best_length = 0
    for category in _CATEGORY_ORDER:
        for keyword in _KEYWORDS[category]:
            if len(keyword) > best_length and keyword in normalized:
                best_category = category
                best_length = len(keyword)
    return best_category
